# Site settings
title: BotsCrew
email: mykolanr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

text:
  contact:
    name:    'Name'
    email:    'Email'
    message:    'Message'
    subject:  'Subject'
    submit:   'submit'
    ajax:
      sending:  'sumbmiting..'
      sent:     'Thanks, we will contact you soon'
      error:    'Error'

menu:
  about: Про компанію
  contact: Контакти
  services: Послуги
  portfolio: Наші роботи
